name: Build Needle n8n nodes

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-needle-n8n-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Build needle-n8n-nodes
        run: pnpm i && pnpm lint && pnpm build
